//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCSOrderSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderTables = new HashSet<OrderTable>();
        }
    
        public int CustNum { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string BankDeatils { get; set; }
        public string Email { get; set; }
        public string AspId { get; set; }
<<<<<<< HEAD
        public string UserName { get; set; }
=======
>>>>>>> 40812cf4cb6c10fd9e96bfd8dac742037e14ea2e
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
    }
}
